services:
  - type: web
    name: certamen-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: true
      - key: OPENAI_API_KEY
        sync: true
      - key: PDF_FOLDER_ID
        sync: true

build:
  packages:
    - poppler-utils     # for pdf2image
    - tesseract-ocr     # for pytesseract OCR
