services:
  - type: web
    name: pdf-chat-ai
    env: docker
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: OPENAI_API_KEY
        sync: true
      - key: GOOGLE_CREDS_JSON
        sync: true
      - key: PDF_FOLDER_ID
        sync: true
